### ISSUE TITLE
Add additional ansible plays and safety checks for aruba CASMNET-2026

### ISSUE THREAD

**Issue by lukebates123** [Cray-HPE/canu#248]
Plays needed

- Copy mgmt interface config from current running config to generated json.
- Set checkpoint on switch before applying config.
- Check for reachability after config is applied.
- Accept checkpoint
- Run tests
CASMNET-2026

### Limitations
-  Have to upload directly to running config.  I was planning on uploading to a checkpoint then copy that to the running config.

![Image](https://user-images.githubusercontent.com/66981180/214390145-2e517399-48f3-4eff-b3cd-241976f8ac1e.png)
We might be able to upload to the startup config.  It works with an 8325 running 10.09.0010, but does not work on aruba a aruba virtual switch.

- We cannot get the mgmt_intf config directly from the API and copy to the running_config.json payload.
```
https://192.168.1.71/rest/v10.09/system?attributes=mgmt_intf&selector=configuration
```
output
```
{
  "mgmt_intf": {
    "admin_state": "up",
    "ip": "192.168.1.71",
    "lldp_trap_enable": true,
    "mode": "static",
    "name": "eth0",
    "subnet_mask": "24"
  }
}
```
From 
```
"https://{{ ansible_host }}/rest/v10.09/configs/running-config"
```
output
```
        "mgmt_intf": {
            "ip": "192.168.1.71",
            "mode": "static",
            "name": "eth0",
            "subnet_mask": "24"
        },
```

The additional fields prevent us from uploading the json payload.

- If you upload the running-config via json after you set a checkpoint timer, the checkpoint feature fails to work.

```
        - name: set checkpoint for one minute "checkpoint auto 1"
          vars:
            ansible_connection: network_cli
          aoscx_command:
            commands:
              - checkpoint auto 1

        # Finally, upload the new config as the running-config
        - name: upload local json config to the running-config
          aoscx_upload_config:
            config_name: "running-config"
            config_json: "{{ validated_config_json }}"
            vrf: "mgmt"
          timeout: 30

        # Accept the checkpoint
        - name: confirm checkpoint "checkpoint auto confirm"
          vars:
            ansible_connection: network_cli
          aoscx_command:
            commands:
              - checkpoint auto confirm
          retries: 5
          delay: 5
```
